const actionTypes = {
    //Auth
    LOGGIN_SUCCESS: 'LOGGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',
    AUTH_REQUEST: 'AUTH_REQUEST',

    //List
    LIST_CREATED: 'LIST_CREATED',
    LIST_UPDATED: 'LIST_UPDATED',
    LIST_DELETED: 'LIST_DELETED',
    FETCH_LISTS_SUCCESS: 'FETCH_LISTS_SUCCESS',
    FIND_ONE_BY_ID: 'FIND_ONE_BY_ID',
    LIST_BY_ID_FETCHED: 'LIST_BY_ID_FETCHED',

    //Todo
    TODO_CREATED: 'TODO_CREATED',
    TODO_UPDATED: 'TODO_UPDATED',
    TODO_DELETED: 'TODO_DELETED',
    TODOS_FETCHED: 'TODOS_FETCHED',
    TODOS_BY_LIST_FETCHED: 'TODOS_BY_LIST_FETCHED',
    COMPLETED_TODOS_FETCHED: 'COMPLETED_TODOS_FETCHED',
    TODO_BY_ID_FETCHED: 'TODO_BY_ID_FETCHED',

    REMOTE_ERROR: 'REMOTE_ERROR',
}

export default actionTypes;