const actionTypes = {
    LOGGIN_SUCCESS: 'LOGGIN_SUCCESS',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    AUTH_ERROR: 'AUTH_ERROR',
    AUTH_REQUEST: 'AUTH_REQUEST',
    REMOTE_ERROR: 'REMOTE_ERROR',
    LIST_CREATED: 'LIST_CREATED',
    LIST_UPDATED: 'LIST_UPDATED',
    FETCH_LISTS_SUCCESS: 'FETCH_LISTS_SUCCESS',
    FIND_ONE_BY_ID: 'FIND_ONE_BY_ID',
}

export default actionTypes;